/**
 * Initial item catalogue for Ethic Brawl story mode.
 */

import type { ItemDefinition } from '@/game/items/item-system';

export type ItemId =
  | 'life_potion_small'
  | 'life_potion_large'
  | 'energy_potion_small'
  | 'energy_potion_large'
  | 'rusted_short_sword'
  | 'neon_duelist_sword'
  | 'street_argument_bat'
  | 'civic_mace'
  | 'riot_breaker_mace'
  | 'pipe'
  | 'uzi'
  | 'bat'
  | 'katana'
  | 'molotov_cocktail'
  | 'grenade'
  | 'boulder'
  | 'rocket_launcher'
  | 'minidrone'
  | 'computer_terminal'
  | 'sniper_rifle'
  | 'bow'
  | 'foldable_chair'
  | 'shovel'
  | 'book_stoic_body'
  | 'book_dialectic_reflexes'
  | 'book_machine_ethics'
  | 'book_arcology_rhetoric'
  | 'temp_boost_adrenaline_patch'
  | 'temp_boost_focus_lens'
  | 'temp_boost_armor_gel'
  | 'temp_boost_overclock_scroll';

export const ITEM_CATALOG: Record<ItemId, ItemDefinition> = {
  life_potion_small: {
    id: 'life_potion_small',
    name: 'Small Life Potion',
    category: 'consumable',
    rarity: 'common',
    description: 'Restore 25 health. Basic survival glue for early story stages.',
    flavorText: 'A red vial labeled: keep arguing.',
    icon: '🧪',
    stackLimit: 3,
    buyValue: 30,
    sellValue: 8,
    effect: { type: 'restore', resource: 'health', amount: 25, amountMode: 'flat' },
    tags: ['life', 'potion', 'healing', 'starter'],
  },
  life_potion_large: {
    id: 'life_potion_large',
    name: 'Large Life Potion',
    category: 'consumable',
    rarity: 'uncommon',
    description: 'Restore 55 health. Strong enough to survive midboss mistakes.',
    flavorText: 'The ingredients are suspiciously optimistic.',
    icon: '🧬',
    stackLimit: 2,
    buyValue: 75,
    sellValue: 18,
    effect: { type: 'restore', resource: 'health', amount: 55, amountMode: 'flat' },
    tags: ['life', 'potion', 'healing'],
  },
  energy_potion_small: {
    id: 'energy_potion_small',
    name: 'Small Energy Potion',
    category: 'consumable',
    rarity: 'common',
    description: 'Restore 30 energy for specials, dashes, and emergency decisions.',
    flavorText: 'Battery acid, monk tea, and neon sugar.',
    icon: '🔋',
    stackLimit: 3,
    buyValue: 35,
    sellValue: 9,
    effect: { type: 'restore', resource: 'energy', amount: 30, amountMode: 'flat' },
    tags: ['energy', 'potion', 'starter'],
  },
  energy_potion_large: {
    id: 'energy_potion_large',
    name: 'Large Energy Potion',
    category: 'consumable',
    rarity: 'uncommon',
    description: 'Restore 70 energy. Best used before elite enemy waves.',
    flavorText: 'The warning label hums louder than the bottle.',
    icon: '⚡',
    stackLimit: 2,
    buyValue: 85,
    sellValue: 20,
    effect: { type: 'restore', resource: 'energy', amount: 70, amountMode: 'flat' },
    tags: ['energy', 'potion'],
  },
  rusted_short_sword: {
    id: 'rusted_short_sword',
    name: 'Rusted Short Sword',
    category: 'weapon',
    rarity: 'common',
    description: 'Simple sword: +4 damage, neutral speed, tiny hitstun gain.',
    flavorText: 'A museum piece repurposed for street philosophy.',
    icon: '🗡️',
    stackLimit: 1,
    buyValue: 90,
    sellValue: 25,
    effect: { type: 'weapon', family: 'sword', damageBonus: 4, speedModifier: 0, hitstunBonus: 1 },
    tags: ['weapon', 'sword', 'starter'],
  },
  neon_duelist_sword: {
    id: 'neon_duelist_sword',
    name: 'Neon Duelist Sword',
    category: 'weapon',
    rarity: 'rare',
    description: 'Fast sword: +7 damage, +8% attack speed, +1 hitstun.',
    flavorText: 'Leaves a citation-shaped afterimage.',
    icon: '⚔️',
    stackLimit: 1,
    buyValue: 190,
    sellValue: 55,
    effect: { type: 'weapon', family: 'sword', damageBonus: 7, speedModifier: 8, hitstunBonus: 1 },
    tags: ['weapon', 'sword', 'fast'],
  },
  street_argument_bat: {
    id: 'street_argument_bat',
    name: 'Street Argument Bat',
    category: 'weapon',
    rarity: 'common',
    description: 'Simple bat: +5 damage, -3% attack speed, +2 hitstun and broad swing reach.',
    flavorText: 'A blunt instrument for debates that left the seminar room.',
    icon: '🏏',
    stackLimit: 1,
    buyValue: 100,
    sellValue: 28,
    effect: { type: 'weapon', family: 'bat', damageBonus: 5, speedModifier: -3, hitstunBonus: 2 },
    tags: ['weapon', 'bat', 'blunt', 'starter'],
  },
  civic_mace: {
    id: 'civic_mace',
    name: 'Civic Mace',
    category: 'weapon',
    rarity: 'common',
    description: 'Heavy mace: +6 damage, -6% attack speed, +3 hitstun.',
    flavorText: 'Democracy, but blunt.',
    icon: '🔨',
    stackLimit: 1,
    buyValue: 110,
    sellValue: 32,
    effect: { type: 'weapon', family: 'mace', damageBonus: 6, speedModifier: -6, hitstunBonus: 3 },
    tags: ['weapon', 'mace', 'stagger'],
  },
  riot_breaker_mace: {
    id: 'riot_breaker_mace',
    name: 'Riot Breaker Mace',
    category: 'weapon',
    rarity: 'rare',
    description: 'Elite mace: +10 damage, -10% attack speed, +5 hitstun.',
    flavorText: 'Made for crowds. Terrible for apologies.',
    icon: '🛠️',
    stackLimit: 1,
    buyValue: 220,
    sellValue: 65,
    effect: {
      type: 'weapon',
      family: 'mace',
      damageBonus: 10,
      speedModifier: -10,
      hitstunBonus: 5,
    },
    tags: ['weapon', 'mace', 'stagger', 'elite'],
  },
  pipe: {
    id: 'pipe',
    name: 'Alley Pipe',
    category: 'weapon',
    rarity: 'common',
    description: 'Quick improvised pipe: +4 damage, -2% attack speed, +2 hitstun.',
    flavorText: 'Civil infrastructure, reclassified as rhetoric.',
    icon: '▰',
    stackLimit: 1,
    buyValue: 85,
    sellValue: 20,
    effect: { type: 'weapon', family: 'pipe', damageBonus: 4, speedModifier: -2, hitstunBonus: 2 },
    tags: ['weapon', 'pipe', 'blunt', 'overlay'],
  },
  uzi: {
    id: 'uzi',
    name: 'Compact Uzi',
    category: 'weapon',
    rarity: 'rare',
    description: 'One-hand ranged weapon: +3 damage, +12% attack speed, low hitstun.',
    flavorText: 'Cheap volume, expensive consequences.',
    icon: '⌁',
    stackLimit: 1,
    buyValue: 260,
    sellValue: 80,
    effect: {
      type: 'weapon',
      family: 'firearm',
      damageBonus: 3,
      speedModifier: 12,
      hitstunBonus: 0,
    },
    tags: ['weapon', 'firearm', 'ranged', 'overlay'],
  },
  bat: {
    id: 'bat',
    name: 'Street Bat',
    category: 'weapon',
    rarity: 'common',
    description: 'Straightforward bat: +5 damage, -3% attack speed, +2 hitstun.',
    flavorText: 'For arguments that need less nuance.',
    icon: '╱',
    stackLimit: 1,
    buyValue: 100,
    sellValue: 28,
    effect: { type: 'weapon', family: 'bat', damageBonus: 5, speedModifier: -3, hitstunBonus: 2 },
    tags: ['weapon', 'bat', 'blunt', 'overlay'],
  },
  katana: {
    id: 'katana',
    name: 'Neon Katana',
    category: 'weapon',
    rarity: 'epic',
    description: 'Precise blade: +9 damage, +6% attack speed, +1 hitstun.',
    flavorText: 'A clean line through a dirty premise.',
    icon: '╲',
    stackLimit: 1,
    buyValue: 320,
    sellValue: 110,
    effect: { type: 'weapon', family: 'katana', damageBonus: 9, speedModifier: 6, hitstunBonus: 1 },
    tags: ['weapon', 'katana', 'blade', 'overlay'],
  },
  molotov_cocktail: {
    id: 'molotov_cocktail',
    name: 'Molotov Cocktail',
    category: 'throwable',
    rarity: 'uncommon',
    description: 'Throwable fire bottle with a small area burst.',
    flavorText: 'An incendiary footnote to civic design.',
    icon: '♨',
    stackLimit: 2,
    buyValue: 120,
    sellValue: 35,
    effect: {
      type: 'throwable',
      projectileId: 'molotov_bottle',
      damage: 18,
      radius: 54,
      throwSpeed: 8,
    },
    tags: ['throwable', 'fire', 'overlay', 'projectile'],
  },
  grenade: {
    id: 'grenade',
    name: 'Grenade',
    category: 'throwable',
    rarity: 'rare',
    description: 'Throwable explosive with a short delayed blast.',
    flavorText: 'Pull pin. Reconsider metaphysics. Throw anyway.',
    icon: '●',
    stackLimit: 2,
    buyValue: 160,
    sellValue: 50,
    effect: {
      type: 'throwable',
      projectileId: 'grenade_arc',
      damage: 28,
      radius: 72,
      throwSpeed: 7,
    },
    tags: ['throwable', 'explosive', 'overlay', 'projectile'],
  },
  boulder: {
    id: 'boulder',
    name: 'Argument Boulder',
    category: 'weapon',
    rarity: 'uncommon',
    description: 'Heavy prop: +12 damage, -18% attack speed, +7 hitstun.',
    flavorText: 'Sisyphus approves of the handling, not the premise.',
    icon: '◖',
    stackLimit: 1,
    buyValue: 180,
    sellValue: 45,
    effect: {
      type: 'weapon',
      family: 'heavy_prop',
      damageBonus: 12,
      speedModifier: -18,
      hitstunBonus: 7,
    },
    tags: ['weapon', 'heavy', 'boulder', 'overlay', 'custom_pose'],
  },
  rocket_launcher: {
    id: 'rocket_launcher',
    name: 'Rocket Launcher',
    category: 'weapon',
    rarity: 'epic',
    description: 'Two-hand launcher: +16 damage, -22% attack speed, +8 hitstun.',
    flavorText: 'A policy disagreement with splash damage.',
    icon: '▱',
    stackLimit: 1,
    buyValue: 420,
    sellValue: 140,
    effect: {
      type: 'weapon',
      family: 'launcher',
      damageBonus: 16,
      speedModifier: -22,
      hitstunBonus: 8,
    },
    tags: ['weapon', 'launcher', 'ranged', 'overlay', 'custom_pose'],
  },
  minidrone: {
    id: 'minidrone',
    name: 'Minidrone',
    category: 'deployable',
    rarity: 'rare',
    description: 'Deploy a tiny harassment drone for a short duration.',
    flavorText: 'A little panopticon with propellers.',
    icon: '◉',
    stackLimit: 1,
    buyValue: 240,
    sellValue: 75,
    effect: {
      type: 'deployable',
      actorId: 'minidrone_actor',
      durationSeconds: 12,
      cooldownSeconds: 20,
    },
    tags: ['deployable', 'drone', 'overlay', 'actor'],
  },
  computer_terminal: {
    id: 'computer_terminal',
    name: 'Portable Computer Terminal',
    category: 'gadget',
    rarity: 'epic',
    description:
      'Hack systems, designate an orbital ion strike, or smash enemies with the terminal casing.',
    flavorText: 'Runs three programs: breach, judgment, blunt force.',
    icon: '▣',
    stackLimit: 1,
    buyValue: 500,
    sellValue: 170,
    effect: {
      type: 'gadget',
      actions: ['hack', 'deploy', 'smash'],
      damageBonus: 8,
      deployableActorId: 'low_orbit_ion_cannon_marker',
      cooldownSeconds: 30,
    },
    tags: ['gadget', 'terminal', 'hack', 'ion_cannon', 'heavy', 'overlay', 'custom_pose'],
  },
  sniper_rifle: {
    id: 'sniper_rifle',
    name: 'Sniper Rifle',
    category: 'weapon',
    rarity: 'epic',
    description: 'Two-hand precision rifle: +14 damage, -14% attack speed, +3 hitstun.',
    flavorText: 'Distance makes every premise look smaller.',
    icon: '━',
    stackLimit: 1,
    buyValue: 390,
    sellValue: 125,
    effect: {
      type: 'weapon',
      family: 'rifle',
      damageBonus: 14,
      speedModifier: -14,
      hitstunBonus: 3,
    },
    tags: ['weapon', 'rifle', 'ranged', 'precision', 'overlay', 'custom_pose'],
  },
  bow: {
    id: 'bow',
    name: 'Tension Bow',
    category: 'weapon',
    rarity: 'uncommon',
    description: 'Silent two-hand ranged weapon: +7 damage, -4% attack speed, +1 hitstun.',
    flavorText: 'Old technology, still undefeated by discourse.',
    icon: ')',
    stackLimit: 1,
    buyValue: 150,
    sellValue: 44,
    effect: { type: 'weapon', family: 'bow', damageBonus: 7, speedModifier: -4, hitstunBonus: 1 },
    tags: ['weapon', 'bow', 'ranged', 'silent', 'overlay', 'custom_pose'],
  },
  foldable_chair: {
    id: 'foldable_chair',
    name: 'Foldable Chair',
    category: 'weapon',
    rarity: 'common',
    description: 'Improvised crowd-control chair: +6 damage, -7% attack speed, +4 hitstun.',
    flavorText: 'A seminar chair in its final, honest form.',
    icon: '▤',
    stackLimit: 1,
    buyValue: 95,
    sellValue: 24,
    effect: { type: 'weapon', family: 'chair', damageBonus: 6, speedModifier: -7, hitstunBonus: 4 },
    tags: ['weapon', 'chair', 'blunt', 'smash', 'overlay'],
  },
  shovel: {
    id: 'shovel',
    name: 'Shovel',
    category: 'weapon',
    rarity: 'common',
    description: 'Long-handled tool weapon: +6 damage, -5% attack speed, +3 hitstun.',
    flavorText: 'For burying bad arguments and occasionally people.',
    icon: '⌞',
    stackLimit: 1,
    buyValue: 105,
    sellValue: 30,
    effect: {
      type: 'weapon',
      family: 'shovel',
      damageBonus: 6,
      speedModifier: -5,
      hitstunBonus: 3,
    },
    tags: ['weapon', 'shovel', 'tool', 'blunt', 'overlay'],
  },
  book_stoic_body: {
    id: 'book_stoic_body',
    name: 'Book: Stoic Body',
    category: 'book',
    rarity: 'common',
    description: 'Permanently gain +8 max health.',
    flavorText: 'Pain is temporary. Marginal HP is forever.',
    icon: '📕',
    stackLimit: 1,
    buyValue: 120,
    sellValue: 30,
    effect: { type: 'permanent_stat', modifiers: [{ stat: 'maxHealth', amount: 8, mode: 'flat' }] },
    tags: ['book', 'permanent', 'health'],
  },
  book_dialectic_reflexes: {
    id: 'book_dialectic_reflexes',
    name: 'Book: Dialectic Reflexes',
    category: 'book',
    rarity: 'uncommon',
    description: 'Permanently gain +2 agility.',
    flavorText: 'Thesis, antithesis, side-step.',
    icon: '📗',
    stackLimit: 1,
    buyValue: 150,
    sellValue: 40,
    effect: { type: 'permanent_stat', modifiers: [{ stat: 'agility', amount: 2, mode: 'flat' }] },
    tags: ['book', 'permanent', 'agility'],
  },
  book_machine_ethics: {
    id: 'book_machine_ethics',
    name: 'Book: Machine Ethics',
    category: 'book',
    rarity: 'uncommon',
    description: 'Permanently gain +2 intelligence.',
    flavorText: 'The footnotes were reviewed by drones.',
    icon: '📘',
    stackLimit: 1,
    buyValue: 150,
    sellValue: 40,
    effect: {
      type: 'permanent_stat',
      modifiers: [{ stat: 'intelligence', amount: 2, mode: 'flat' }],
    },
    tags: ['book', 'permanent', 'intelligence'],
  },
  book_arcology_rhetoric: {
    id: 'book_arcology_rhetoric',
    name: 'Book: Arcology Rhetoric',
    category: 'book',
    rarity: 'rare',
    description: 'Permanently gain +2 strength and +1 defense.',
    flavorText: 'Convince the tower you deserve to reach the penthouse.',
    icon: '📙',
    stackLimit: 1,
    buyValue: 240,
    sellValue: 75,
    effect: {
      type: 'permanent_stat',
      modifiers: [
        { stat: 'strength', amount: 2, mode: 'flat' },
        { stat: 'defense', amount: 1, mode: 'flat' },
      ],
    },
    tags: ['book', 'permanent', 'strength', 'defense'],
  },
  temp_boost_adrenaline_patch: {
    id: 'temp_boost_adrenaline_patch',
    name: 'Adrenaline Patch',
    category: 'temporary_boost',
    rarity: 'common',
    description: 'For the next fight: +15% agility.',
    flavorText: 'The patch argues with your bloodstream.',
    icon: '💉',
    stackLimit: 2,
    buyValue: 70,
    sellValue: 15,
    effect: {
      type: 'temporary_boost',
      durationFights: 1,
      modifiers: [{ stat: 'agility', amount: 15, mode: 'percent' }],
    },
    tags: ['temporary', 'boost', 'speed'],
  },
  temp_boost_focus_lens: {
    id: 'temp_boost_focus_lens',
    name: 'Focus Lens',
    category: 'temporary_boost',
    rarity: 'uncommon',
    description: 'For the next two fights: +10% intelligence.',
    flavorText: 'Sharpens special attacks and complicated decisions.',
    icon: '🔍',
    stackLimit: 2,
    buyValue: 90,
    sellValue: 22,
    effect: {
      type: 'temporary_boost',
      durationFights: 2,
      modifiers: [{ stat: 'intelligence', amount: 10, mode: 'percent' }],
    },
    tags: ['temporary', 'boost', 'intelligence'],
  },
  temp_boost_armor_gel: {
    id: 'temp_boost_armor_gel',
    name: 'Armor Gel',
    category: 'temporary_boost',
    rarity: 'uncommon',
    description: 'For the next fight: +20% defense.',
    flavorText: 'Smells like plastic ethics.',
    icon: '🧴',
    stackLimit: 2,
    buyValue: 95,
    sellValue: 24,
    effect: {
      type: 'temporary_boost',
      durationFights: 1,
      modifiers: [{ stat: 'defense', amount: 20, mode: 'percent' }],
    },
    tags: ['temporary', 'boost', 'defense'],
  },
  temp_boost_overclock_scroll: {
    id: 'temp_boost_overclock_scroll',
    name: 'Overclock Scroll',
    category: 'temporary_boost',
    rarity: 'rare',
    description: 'For the next fight: +10% strength and +10% agility.',
    flavorText: 'Ancient paper, modern firmware.',
    icon: '📜',
    stackLimit: 1,
    buyValue: 160,
    sellValue: 45,
    effect: {
      type: 'temporary_boost',
      durationFights: 1,
      modifiers: [
        { stat: 'strength', amount: 10, mode: 'percent' },
        { stat: 'agility', amount: 10, mode: 'percent' },
      ],
    },
    tags: ['temporary', 'boost', 'strength', 'speed'],
  },
};

export const STARTER_ITEM_IDS: readonly ItemId[] = [
  'life_potion_small',
  'energy_potion_small',
  'rusted_short_sword',
  'book_stoic_body',
];

export function getItem(itemId: ItemId): ItemDefinition {
  return ITEM_CATALOG[itemId];
}

export function getItemsByCategory(category: ItemDefinition['category']): ItemDefinition[] {
  return Object.values(ITEM_CATALOG).filter((item) => item.category === category);
}
